services:
  - type: web
    name: papirorun
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - vite.config.ts